### ISSUE TITLE
A warm hello from earthobservations

### ISSUE THREAD

**Issue by gutzbenj** [guidocioni/mosmix-webapp#1]
Dear Guido,

thanks a stack for your feedback on our library at [1] and [2], we appreciate it very much. We always wanted to answer your letter at [3] more thoroughly in order to get closer in touch with you. We really like what you are doing there and wanted to take the chance to inform you that Wetterdienst just recently also gained a Dash-based user interface [4].

So, if that would also resonate with you, we would like to humbly invite you to our organization at "earthobservations". If you also like what we are doing here, it would be precious if we could join forces in one way or another.

With kind regards,
Benjamin, Andreas and Matthias.

[1] https://github.com/earthobservations/wetterdienst/issues/356
[2] https://github.com/earthobservations/wetterdienst/issues/412
[3] https://github.com/earthobservations/wetterdienst/discussions/362
[4] https://github.com/earthobservations/wetterdienst/pull/398

**Comment by guidocioni** [comment]
Moin Guys,
thanks for the kind words.
It would be an honor for me to contribute to the project if I can in any way with my poor Python knowledge 😛
This project would be pretty easy to include, as wetterdienst-ui. For the model part of course it is a little bit more complicated but super interesting!

**Comment by gutzbenj** [comment]
Ciao Guido,
we are glad to hear back from you! I'll just add you to the group and furthermore we have an internal chat, so if you wish we could also add you there, just a warning atm we are mostly speaking german there, but we can change that as well^^

**Comment by guidocioni** [comment]
> Ciao Guido,
> we are glad to hear back from you! I'll just add you to the group and furthermore we have an internal chat, so if you wish we could also add you there, just a warning atm we are mostly speaking german there, but we can change that as well^^

wenn für euch auch Hamburgisch passt ist für mich in Ordnung 😛

**Comment by guidocioni** [comment]
Hello @gutzbenj. I just realized we never actually talked about this :D What you think about the idea of having an informal chat in the next days about ongoing projects?
